kind: Service
apiVersion: v1
metadata:
  name: superhero-django-api-svc
spec:
  selector:
    app: backend-superhero-django-api
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP
